git:
  depth: 1
language: cpp
dist: xenial
os:
  - osx
  - linux
  - windows
script:
  - echo $TRAVIS_OS_NAME
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then gcc --version; fi
  - python fips clean
    # OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-release; fi
    # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-release; fi
    # Windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build win64-vstudio-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build win64-vstudio-release; fi

